name: Push

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  shared:
    name: Shared
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v5

    - name: Configure JDK
      uses: actions/setup-java@v5
      with:
       distribution: 'temurin'
       java-version: '17'

    - name: Load secrets
      run: echo "tfl_app_key=${{ secrets.TFL_APP_KEY }}" > shared/secret.properties

    - name: Check
      run: ./gradlew spotlessCheck

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew allTests

    - name: Publish test results
      uses: dorny/test-reporter@v2.1.1
      if: always()
      with:
        name: Test results
        path: '**/build/test-results/**/TEST-*.xml'
        reporter: java-junit
        fail-on-error: true

  macOS:
    name: macOS app
    runs-on: macos-26
    steps:

    - uses: actions/checkout@v5

    - name: Configure Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '26.1'

    - name: Configure JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Load secrets
      run: echo "tfl_app_key=${{ secrets.TFL_APP_KEY }}" > shared/secret.properties

    - name: Build
      run: |
        xcodebuild -project macOS/Arrivals.xcodeproj \
          -scheme Arrivals \
          -configuration Debug build

    - name: Test
      run: |
        xcodebuild test \
          -project macOS/Arrivals.xcodeproj \
          -scheme Arrivals \
          -destination 'platform=macOS'
